allure-junit-adaptor/src/main/java/ru/yandex/qatools/allure/junit/AllureRunListener.java

Don't start all suites at run start

---

allure-java-adaptor-api/src/main/java/ru/yandex/qatools/allure/storages/TestCaseStorage.java
allure-java-adaptor-api/src/test/java/ru/yandex/qatools/allure/AllureLifecycleTest.java
allure-junit-adaptor/pom.xml
allure-junit-adaptor/src/test/java/ru/yandex/qatools/allure/junit/AllureListenerTimeoutTest.java
allure-junit-adaptor/src/test/java/ru/yandex/qatools/allure/junit/AllureListenerXmlValidationTest.java
allure-junit-adaptor/src/test/java/ru/yandex/qatools/allure/junit/BasicListenerTest.java
allure-junit-adaptor/src/test/java/ru/yandex/qatools/allure/junit/testdata/TestWithTimeoutAnnotation.java
allure-junit-adaptor/src/test/java/ru/yandex/qatools/allure/junit/testdata/TestWithTimeoutRule.java

Add tests to detect the problem 475

---

allure-report-face/pom.xml

fight for smaller size of reports

exclude unused files from package

---

allure-e2e/pom.xml
allure-report-face/pom.xml

use actual allure-face content in integration tests
addition to #485

add missing resource

---

allure-java-adaptor-api/src/main/java/ru/yandex/qatools/allure/utils/AnnotationManager.java

change thread label format  from `<user>@<host>.<thread-name>` to `<user>@<host>.<thread-name>(<thread-id>)`

change thread label format (#496)

---

allure-report-face/src/main/webapp/js/testcase/testcase.js
allure-report-face/src/main/webapp/templates/testcase/testcase.html

@baev @just-boris 
Please review if this pull request makes sense.
P.S. However I like unaligned icons variant more

Making test step statuses more visible

---

allure-report-face/src/main/webapp/index.html

add pointer into language select

---

allure-report-face/src/main/webapp/index.html
allure-report-face/src/main/webapp/js/controllers.js
allure-report-face/src/test/webapp/unit/controllersSpec.js

save selected language

---

allure-report-face/src/main/webapp/js/testcase/testcase.js
allure-report-face/src/main/webapp/templates/testcase/attachment.html

CSV attachment viewer (#438)

---

allure-report-face/pom.xml

Fix context path

---

allure-report-face/src/main/webapp/templates/testcase/testcase.html

Itial touch on #532 
@baev, @just-boris -- please, have a look

Show duration as well as start time for test step

---

allure-report-face/src/main/less/app.less
allure-report-face/src/main/less/islands/vert.less
allure-report-face/src/main/webapp/index.html
allure-report-face/src/main/webapp/js/controllers.js
allure-report-face/src/main/webapp/translations/en.json
allure-report-face/src/main/webapp/translations/ru.json

Can save up to 5% of screen if no need to click on tabs every time
Hilight on hover
Left align

add - collapsed menu with one extra-btn

---

allure-report-face/src/main/webapp/templates/testcase/testcase.html

do not expand stacktrace on click

---

allure-report-data/src/main/groovy/ru/yandex/qatools/allure/data/plugins/BehaviorsPlugin.groovy
allure-report-data/src/main/resources/META-INF/services/ru.yandex.qatools.allure.data.plugins.Plugin
allure-report-data/src/test/groovy/ru/yandex/qatools/allure/data/plugins/BehaviorsPluginTest.groovy
allure-report-data/src/test/java/ru/yandex/qatools/allure/data/AllureReportGeneratorTest.java
allure-report-face/src/main/webapp/index.html
allure-report-face/src/main/webapp/js/app.js
allure-report-face/src/main/webapp/js/behaviors/BehaviorsCtrl.js
allure-report-face/src/main/webapp/templates/behaviors.html
allure-report-face/src/test/webapp/unit/behaviors/BehaviorsCtrlSpec.js

Good for naming consistency.
Preparing to move this tab into plugin

rename features -> behaviors

---

allure-model/src/main/resources/environment.xsd
allure-model/src/test/resources/allure-results/environment.xml
allure-report-data/src/main/groovy/ru/yandex/qatools/allure/data/io/ReportWriter.groovy
allure-report-data/src/main/groovy/ru/yandex/qatools/allure/data/plugins/EnvironmentPlugin.groovy
allure-report-data/src/main/resources/xsd/report-data.xsd
allure-report-data/src/test/groovy/ru/yandex/qatools/allure/data/plugins/EnvironmentPluginTest.groovy
allure-report-face/src/main/webapp/index.html

Add launch name and url to header (#583)

---

allure-report-face/src/main/webapp/plugins/xunit/testsuite.html

Impossible to close Testsuite view

---

allure-java-adaptor-api/src/main/java/ru/yandex/qatools/allure/utils/AllureResultsUtils.java
allure-java-adaptor-api/src/test/java/ru/yandex/qatools/allure/utils/WriteAttachmentTest.java
allure-model/src/main/resources/allure.xsd
allure-model/src/test/resources/allure-results/c32503a8-2981-43da-afa5-e0d82dacfefd-testsuite.xml
allure-report-data/src/main/groovy/ru/yandex/qatools/allure/data/converters/DefaultTestCaseConverter.groovy
allure-report-data/src/test/groovy/ru/yandex/qatools/allure/data/converters/DefaultTestCaseConverterTest.groovy

Move attachments size calculation to the report side (#540)

---

allure-report-face/src/main/webapp/index.html

~~do not merge. It is just for test now~~
ready to merge

force to disable compability mode in IE

---

allure-report-face/pom.xml
allure-report-face/src/main/less/app.less
allure-report-face/src/main/less/base.less
allure-report-face/src/main/webapp/index.html
allure-report-face/src/main/webapp/js/controllers.js

It is nice to see full name instead of abbreviation

change display name for locale

---

allure-testng-adaptor/src/main/java/ru/yandex/qatools/allure/testng/AllureTestListener.java
allure-testng-adaptor/src/test/java/ru/yandex/qatools/allure/testng/AllureTestListenerConfigMethodsTest.java
allure-testng-adaptor/src/test/java/ru/yandex/qatools/allure/testng/AllureTestListenerMultipleSuitesTest.java
allure-testng-adaptor/src/test/java/ru/yandex/qatools/allure/testng/AllureTestListenerTest.java
allure-testng-adaptor/src/test/java/ru/yandex/qatools/allure/testng/AllureTestListenerXmlValidationTest.java
allure-testng-adaptor/src/test/java/ru/yandex/qatools/allure/testng/AllureTestUtils.java
allure-testng-adaptor/src/test/java/ru/yandex/qatools/allure/testng/testdata/ConfigMethodsTest.java

I made a lot of changes to the testNg adapter, can somebody test it?  
Unfortunately I'm hitting some problems when I tying to build the Allure project on my Windows 7 machine.

Fixing #569 and other testNg cumulative issues

---

allure-report-data/src/main/groovy/ru/yandex/qatools/allure/data/converters/DefaultTestCaseConverter.groovy
allure-report-data/src/main/groovy/ru/yandex/qatools/allure/data/index/DefaultAttachmentIndex.groovy
allure-report-data/src/main/groovy/ru/yandex/qatools/allure/data/io/ReportWriter.groovy
allure-report-data/src/main/java/ru/yandex/qatools/allure/data/AllureGuiceModule.java
allure-report-data/src/main/java/ru/yandex/qatools/allure/data/io/AttachmentReader.java
allure-report-data/src/test/groovy/ru/yandex/qatools/allure/data/converters/DefaultTestCaseConverterTest.groovy
allure-report-data/src/test/groovy/ru/yandex/qatools/allure/data/io/AttachmentReaderTest.groovy
allure-report-data/src/test/java/ru/yandex/qatools/allure/data/AllureReportGeneratorTest.java
allure-report-plugin-api/src/main/java/ru/yandex/qatools/allure/data/plugins/AttachmentIndex.java
allure-report-plugin-api/src/main/resources/xsd/testcases.xsd

* Some code optimizations; 
* new `AttachmentIndex` injection available for plugins.

Add attachment index

---

allure-report-data/src/main/groovy/ru/yandex/qatools/allure/data/plugins/TotalPlugin.groovy
allure-report-data/src/main/resources/META-INF/services/ru.yandex.qatools.allure.data.plugins.Plugin
allure-report-data/src/main/resources/xsd/total-plugin.xsd
allure-report-face/src/main/webapp/js/overview/widgets.js
allure-report-face/src/main/webapp/plugins/total/script.js
allure-report-face/src/main/webapp/templates/overview.html
allure-report-face/src/main/webapp/templates/overview/total.html
allure-report-plugin-api/src/main/java/ru/yandex/qatools/allure/data/plugins/TotalWidget.java
allure-report-plugin-api/src/main/resources/xsd/widgets.xsd

Add total info  widget

---

allure-model/src/test/resources/allure-results/c32503a8-2981-43da-afa5-e0d82dacfefd-testsuite.xml
allure-report-face/src/main/less/blocks/widget.less

preserve widget width with long strings

---

allure-report-face/src/main/less/app.less

add built-in angular styles

---

allure-java-adaptor-api/pom.xml
allure-java-adaptor-api/src/main/java/ru/yandex/qatools/allure/Allure.java
allure-java-adaptor-api/src/test/java/ru/yandex/qatools/allure/AllureTest.java
allure-java-adaptor-api/src/test/java/ru/yandex/qatools/allure/utils/AllureResultsHelperTest.java
allure-java-adaptor-api/src/test/java/ru/yandex/qatools/allure/utils/testdata/TestData.java
pom.xml

Remove attachments from passed tests bug fix

---

allure-report-data/src/main/java/ru/yandex/qatools/allure/io/TestCaseResultIterator.java
allure-report-data/src/test/groovy/ru/yandex/qatools/allure/io/TestCaseReaderTest.groovy

Remove duplicate labels

---

allure-report-data/src/main/groovy/ru/yandex/qatools/allure/plugins/XUnitPlugin.groovy
allure-report-data/src/main/groovy/ru/yandex/qatools/allure/utils/PluginUtils.groovy
allure-report-data/src/test/groovy/ru/yandex/qatools/allure/utils/PluginUtilsTest.groovy

Add sorting to xunit widget

---

allure-report-face/src/data/settings/SettingsModel.js

That was made for tests, should not be default

change default language

---

allure-report-face/src/components/steps/steps-list.hbs

use step title instead of name

---

allure-model/src/test/resources/allure-results/00a0bc5a-6372-4e66-8088-1571966a056b-attachment.uri
allure-report-face/src/components/attachment/AttachmentView.hbs
allure-report-face/src/components/attachment/AttachmentView.js
allure-report-face/src/components/attachment/styles.css
allure-report-face/src/helpers/splitUriList.js
allure-report-face/src/variables.css

in follow to #778 
* don't use tables
* remove helper

update uri viewer

---

allure-report-face/src/helpers/date.js

fixes #812
That was embarrassing.

fix date formatting

---

allure-testng-adaptor/src/main/java/ru/yandex/qatools/allure/testng/AllureTestListener.java

This pull request is focused on resolving occurrences of Sonar rule pmd:UseProperClassLoader - Use Proper Class Loader
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:UseProperClassLoader
Please let me know if you have any questions.
M-Ezzat

pmd:UseProperClassLoader - Use Proper Class Loader

---

allure-report-face/src/components/testcase-table/TestcaseTableView.hbs
allure-report-face/test/components/testcase-table.spec.js

Fixed an issue with title displaying on test cases' table view, when test name was displayed instead of a title (see https://github.com/allure-framework/allure-core/issues/825).

Test case title fix

---

allure-report-face/src/app.js
allure-report-face/src/index.js
allure-report-face/src/util/translation.js

We should defer first loading upon all localization files will be loaded.
**this fix is WIP, don't merge**

Prevent double rendering of views

---

allure-model/src/main/java/ru/yandex/qatools/allure/config/AllureConfig.java
allure-testng-adaptor/src/main/java/ru/yandex/qatools/allure/testng/AllureTestListener.java

Commit 018ef6baf4a331e78b68f91150f55d676fd02fe0 from @sskorol

Merge fix for disabling testNG params from master to 1.4.x branch

---

allure-java-aspects/src/main/java/ru/yandex/qatools/allure/aspects/AllureAttachAspects.java

See https://github.com/allure-framework/allure-core/issues/889.

Fixed NPE in processing null-returning attachment methods (fixes #889)

---

LICENSE
allure-model/src/test/resources/allure-results/c32503a8-2981-43da-afa5-e0d82dacfefd-testsuite.xml
allure-report-data/src/main/groovy/ru/yandex/qatools/allure/data/converters/DefaultTestCaseConverter.groovy
allure-report-data/src/main/groovy/ru/yandex/qatools/allure/data/utils/PluginUtils.groovy
allure-report-data/src/test/java/ru/yandex/qatools/allure/data/AllureReportGeneratorTest.java
allure-report-face/src/plugins/testcase-links/LinksView.hbs
allure-report-face/src/plugins/testcase-links/LinksView.js
allure-report-plugin-api/src/main/resources/xsd/testcases.xsd

example in some one testsuite.xml:
```xml
<labels>
<label name="thread" value="13758680"/>
<label name="host" value="debian-wuhuizuo"/>
<label name="testId" value="429265"/>
<label name="testId" value="123456"/>
</labels>
```
there has two testId labels for the testcase,then the report will display two testId.

Support multi testId for one test like issue
