allure-framework/allure1

- allure-java-adaptor-api/src/main/java/ru/yandex/qatools/allure/events/AddParameterEvent.java
- allure-java-adaptor-api/src/main/resources/allure.events.xsd
- allure-java-annotations/src/main/java/ru/yandex/qatools/allure/annotations/Parameter.java
- allure-testng-adaptor/src/main/java/ru/yandex/qatools/allure/testng/AllureTestListener.java
- allure-testng-adaptor/src/test/java/ru/yandex/qatools/allure/testng/AllureTestListenerTest.java
This is first step to support parametrized tests (@ DataProvider in TestNG, @ Parameters in JUnit). TestNG adapter only. 
- In XML parameter kind 'ARGUMENT' is used. 
- Later support on UI will be added.
- If compiled by Java 8 with javac -parameters, real test method argument names will be taken. 
- Java 7 compatible.
> Adding parametrized (TestNG) test support (back-end)

- allure-model/src/test/resources/allure-results/a179d781-ed1f-4d54-b146-59984be84462-testsuite.xml
- allure-report-face/src/main/less/blocks/testcase.less
- allure-report-face/src/main/webapp/js/testcase/testcase.js
- allure-report-face/src/main/webapp/templates/testcase/testcase.html
- allure-report-face/src/main/webapp/translations/en.json
- allure-report-face/src/main/webapp/translations/ru.json
- allure-report-face/src/test/webapp/core/testcase/testcaseSpec.js
@just-boris UI part of https://github.com/allure-framework/allure-core/pull/534
Views can be still played around with. Providing several variants:
1. Huge text, JSON style parameters, sliders icon:
2. Current pull request:
Sample test suite my.company.ParametrizedTest XML has been updated (allure-model module).
P.S. If allure-test-case-info in testcase.xsd is extended with parameters it will be possible to see them in test case list as well:
But may be that will break Allure table simplicity.
> Adding parametrized (TestNG) test support (front-end)

- allure-junit-adaptor/pom.xml
- allure-testng-adaptor/pom.xml
Now you can use `spi-off` classifier do disable adaptors loading via SPI
> Add packaging without services for adapters

- allure-testng-adaptor/src/main/java/ru/yandex/qatools/allure/testng/AllureTestListener.java
- allure-testng-adaptor/src/test/java/ru/yandex/qatools/allure/testng/AllureTestListenerTest.java
- Processing all the annotated parameters instead of returning on first non-annotated parameter
- Fixing warnings in `isAfterSuiteConfigMethod()`
> Fixing bug with method parameters

- allure-report-face/src/main/webapp/plugins/xunit/testrun.html
xUnit plugin: test run status order is not consistent with both filter buttons and Behaviours plugin.
Before:
After:
> xUnit: consistent order of test run statuses

- allure-report-face/src/main/webapp/templates/testcase/testcase.html
This is was used earlier, but now we don't need to break step titles by this way
> remove undesired line-breaking

- allure-report-face/src/main/webapp/js/testcase/testcase.js
- allure-report-face/src/main/webapp/templates/testcase/attachment.html
- image/svg+xml mime type
- Interactive (javascript) svg supported
- `<object/>` was used as recommended at http://www.sitepoint.com/add-svg-to-web-page/ - interactive images are supported.
- HTML contains fallback: "Your browser does not support SVG". All modern browsers do support SVG. Regular user will never see it. So, the message is not translated to minimize localization (maintenance) cost.
> SVG attachment viewer

- allure-java-adaptor-api/src/main/java/ru/yandex/qatools/allure/utils/AllureResultsUtils.java
- allure-java-adaptor-api/src/test/java/ru/yandex/qatools/allure/utils/WriteTestSuiteResultTest.java
Hi,
Deleting suite XML file from allure-results directory fails with IO exception ("The process cannot access the file because it is being used by another process"). JAXB marshaller does not close the file Writer, it should be done explicitly. 
Thanks!
> bug fix: close result file writer

- allure-bundle/pom.xml
- allure-bundle/src/assembly/standalone-bundle.xml
- allure-commandline/pom.xml
- allure-report-preview/pom.xml
- pom.xml
* Move preview module to the end of the build cycle.
* Bundle now has `standalone` classifier for executable version (super jar). 
* Use bundle to generate preview
> Use bundle to generate preview

- pom.xml
Can't build `allure-core` at Windows, cause https://java.net/jira/browse/JAXB-1070 , so need to downgrade jaxb plugin
> Downgrade jaxb plugin version

- allure-java-adaptor-api/src/main/java/ru/yandex/qatools/allure/utils/AllureResultsHelper.java
- allure-junit-adaptor/src/test/java/ru/yandex/qatools/allure/AllureListenerTimeoutTest.java
- allure-junit-adaptor/src/test/java/ru/yandex/qatools/allure/AllureListenerXmlValidationTest.java
- allure-model/src/main/java/ru/yandex/qatools/allure/AllureConstants.java
- allure-model/src/main/java/ru/yandex/qatools/allure/AllureUtils.java
- allure-model/src/test/java/ru/yandex/qatools/allure/AllureUtilsTest.java
- allure-model/src/test/resources/allure-results/sample-json-testsuite.json
- allure-report-data/pom.xml
- allure-report-data/src/main/java/ru/yandex/qatools/allure/io/AbstractResultIterator.java
- allure-report-data/src/main/java/ru/yandex/qatools/allure/io/JsonTestSuiteResultIterator.java
- allure-report-data/src/main/java/ru/yandex/qatools/allure/io/TestCaseReader.java
- allure-report-data/src/main/java/ru/yandex/qatools/allure/io/TestCaseResultIterator.java
- allure-report-data/src/main/java/ru/yandex/qatools/allure/io/TestCaseResultIterator2.java
- allure-report-data/src/main/java/ru/yandex/qatools/allure/io/TestSuiteReader.java
- allure-report-data/src/main/java/ru/yandex/qatools/allure/io/XmlTestSuiteResultIterator.java
- allure-report-data/src/test/groovy/ru/yandex/qatools/allure/io/TestCaseReaderTest.groovy
- allure-report-data/src/test/groovy/ru/yandex/qatools/allure/io/TestSuiteReaderTest.groovy
- allure-report-data/src/test/java/ru/yandex/qatools/allure/AllureReportGeneratorTest.java
- allure-testng-adaptor/src/test/java/ru/yandex/qatools/allure/AllureTestListenerConfigMethodsTest.java
- allure-testng-adaptor/src/test/java/ru/yandex/qatools/allure/AllureTestListenerMultipleSuitesTest.java
- allure-testng-adaptor/src/test/java/ru/yandex/qatools/allure/AllureTestListenerSuiteNameTest.java
- allure-testng-adaptor/src/test/java/ru/yandex/qatools/allure/AllureTestListenerXmlValidationTest.java
```json
{
"name": "other.PassingTest",
"start": 1412949538848,
"stop": 1412949560045,
"version": "1.4.4-SNAPSHOT",
"testCases": [
{
"name": "testPassed",
"start": 1412949529363,
"stop": 1412949549730,
"status": "PASSED",
"labels": [
{
"name": "issue",
"value": "JIRA-15"
},
{
"name": "testId",
"value": "TMS-1"
}
]
}
],
"labels": [
{
"name": "story",
"value": "SuccessStory"
}
]
}
```
> Add ability to process results in json format

- allure-report-face/src/main/webapp/plugins/defects/tab.tpl.html
In some case will be nice to see multiline defect description in Defects widget.
This commit very small and safe)
> Allow multiline in Defects widget

- allure-model/src/main/java/ru/yandex/qatools/allure/config/AllureConfig.java
- allure-testng-adaptor/src/main/java/ru/yandex/qatools/allure/testng/AllureTestListener.java
Proposal request: for users, who has lots of parameters (in suite xml) or heavy entities (produced e.g. by DataProvider) in tests, it's quite annoying to see all of them in every report's title (suite name, testcase name, test headers).
In the following PR there was introduced a new property **allure.are.testng.parameters.disabled**, which is **false** by default to avoid any issues for existing users. But if someone wants to disable parameters rendering, he could just set corresponding property = **true**.
> Feature: disable testng parameters rendering

- allure-model/src/test/resources/allure-results/00a0bc5a-6372-4e66-8088-1571966a056b-attachment.uri
- allure-model/src/test/resources/allure-results/c32503a8-2981-43da-afa5-e0d82dacfefd-testsuite.xml
- allure-report-data/src/test/java/ru/yandex/qatools/allure/data/AllureReportGeneratorTest.java
- allure-report-face/src/components/attachment/AttachmentView.hbs
- allure-report-face/src/components/attachment/AttachmentView.js
- allure-report-face/src/helpers/splitUriList.js
- allure-report-face/src/util/attachmentType.js
See initial request #412 
Motivation: to avoid loading heavy attachments into report's context, it'd be nice to be able to attach just a list of URIs for further manual downloading.
Adding URI as a return type will affect core and require some effort on refactoring. 
Current approach assumes pure report face involvement. Implementation itself is based on `text/uri-list` mime type.
As input user could use the following syntax:
```java
@Attachment(value = "{0}", type = "text/uri-list")
public String saveLinks(final String attachName, final List<String> uris) {
return uris.stream().collect(joining(System.lineSeparator()));
}
```
As output there will be provided a table-based list of links.
<a href="http://www.imagecross.com/"><img src="http://hostingd.imagecross.com/image-hosting-08/4827uri-l …
> Feature: uri-list support

- allure-report-face/src/helpers/duration.js
- allure-report-face/src/plugins/timeline/TimelineView.js
- allure-report-face/test/helpers/duration.spec.js
It haven't done before because that looked not good on our example 
Now I added workaround for it.
Fixes #815
> Add more digits for timeline

- allure-model/src/main/java/ru/yandex/qatools/allure/config/AllureModelUtils.java
- allure-model/src/main/resources/allure.xsd
- allure-testng-adaptor/src/main/java/ru/yandex/qatools/allure/testng/AllureTestListener.java
- allure-testng-adaptor/src/test/java/ru/yandex/qatools/allure/testng/AllureTestListenerTest.java
- according to #558 and #610 requests, there were added additional labels for further adaptor improvements and plugins development;
- testng-adaptor will now supply 4 additional labels into TestCases for easier filtering by suites / groups / classes / test names.
> New labels as a part of testng-adaptor improvements

- allure-report-face/src/main/webapp/templates/testcase/testcase.html
As you can see on the screenshot icon and label can't be broken by new line any more. As a side effect label font decreased slightly (which is good IMO, since it visually is not mixed with values any more).
> Test case details: minor visual improvement

- allure-report-face/src/main/webapp/js/charts/pie.js
This is already fixed in master. But (since we have to support our Allure plugins for transition period) we would like to have it in 1.4.x branch as well.
Before:
After:
> pie chart: percentage precision is 2 to postpone "100% passed" issue

- allure-testng-adaptor/src/main/java/ru/yandex/qatools/allure/testng/AllureTestListener.java
- allure-testng-adaptor/src/test/java/ru/yandex/qatools/allure/testng/AllureTestListenerGroupsTest.java
- allure-testng-adaptor/src/test/java/ru/yandex/qatools/allure/testng/testdata/GroupTest.java
- allure-testng-adaptor/src/test/resources/suite-groups.xml
This fixes the issue described in #880
> Methods that are excluded by a "groups" filter must not be included in the report

- allure-junit-adaptor/src/main/java/ru/yandex/qatools/allure/junit/AllureRunListener.java
- allure-junit-adaptor/src/test/java/ru/yandex/qatools/allure/junit/AllureRunListenerTest.java
Some frameworks based on top of JUnit don't provide real class names in `Description` (which is totally legal, see motivation below), so trying to do something like this:
```java
Description.createSuiteDescription(description.getTestClass());
```
lead us to `NullPointerException`, cause inside `Desrctiption#createSuiteDescription(Class<?>)` we have:
```java
return new Description(testClass, testClass.getName(), testClass.getAnnotations());
```
Copy-paste from JUnit
```java
/**
* Create a <code>Description</code> of a single test named <code>name</code> in the 'class' named
* <code>className</code>. Generally, this will be a leaf <code>Description</code>. This method is a better choice
* than {@link #createTestDescription(Class, String, Annotation...)} for test runners whose test cases are …
```
> [JUNIT] Fixed bug with relying on class inside description
